In [1]:
import numpy as np

In [2]:
np.sqrt(17)  # квадратный корень 

4.123105625617661

In [3]:
np.log(4)  # натуральный логарифм

1.3862943611198906

In [4]:
np.mean([20, 40, 30, 450, 45, 30])  # среднее

102.5

In [5]:
np.median([20, 40, 30, 450, 45, 30])  # медиана

35.0

In [6]:
marks = np.array([5, 4, 3, 5, 5, 4, 3, 4]) 
marks

array([5, 4, 3, 5, 5, 4, 3, 4])

In [7]:
marks.min()

3

In [8]:
marks.max()

5

In [9]:
marks.mean()

4.125

In [10]:
marks.argmax() # номер самой высокой оценки

0

In [11]:
marks.argmin() # номер самой низкой оценки

2

In [12]:
grades = np.array([[3, 5, 5, 4, 3], 
          [3, 3, 4, 3, 3], 
          [5, 5, 5, 4, 5]])

In [13]:
grades.mean(axis = 1) # по строкам, три оценки - одна для каждой группы

array([4. , 3.2, 4.8])

In [14]:
grades.mean(axis = 0) # по столбцам, пять оценки - одна для каждой работы

array([3.66666667, 4.33333333, 4.66666667, 3.66666667, 3.66666667])

In [15]:
np.arange(2, 9, 3) # создание массива с шагом 3

array([2, 5, 8])

In [16]:
Z = np.zeros((3, 3)) # размеры в виде кортежа - не теряйте еще одни круглые скобки
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
O = np.ones((4, 2))
O

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
E = np.eye(5)
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])